### ISSUE TITLE
Links in entries/posts don't work

### ISSUE THREAD

**Issue by emacsomancer** [areina/elfeed-cljsrn#11]
Issue: Clicking/tapping a link within an entry/post just opens a blank page.

 Expected behaviour: Clicking a link in an entry/post should trigger opening a browser

[Side related nitpick: For the general "open in browser" function - does it need to be within a three-dot menu which only has one item?  Couldn't it just be (1 tap) icon like the "mark unread" button?]

**Comment by areina** [comment]
Yes, I'll try to fix it as soon as possible.

About the menu, I thought the number of actions would increase quickly, but I was wrong :-) I will reconsider it

**Comment by areina** [comment]
Both things have been addressed in the latest version.
