### ISSUE TITLE
Add application to F-droid

### ISSUE THREAD

**Issue by increasingawareness** [areina/elfeed-cljsrn#15]
I love using Elfeed on my laptop and would love to use Elfeed on my mobile that doesn't have access to play store. If there is anyway to package the APK for https://f-droid.org that would be amazing! Plus, I'll open a bounty :-)

**Comment by increasingawareness** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=47281858)](https://www.bountysource.com/issues/47281858-add-application-to-f-droid?utm_source=47281858&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by areina** [comment]
Hi! Right, it would be nice having the app available for download in f-droid.org. I tried it some time ago, and it was almost impossible because they don't have a way to support apps developed in React Native. I'll take a look again, but meanwhile you could download&install the APK directly from [Github releases](https://github.com/areina/elfeed-cljsrn/releases)

**Comment by ghost** [comment]
Actually there many react native app in f-droid the problem is use some google privative library

**Comment by slackline** [comment]
Would there be any objection to submitting this for inclusion?

I was going to do so, but need to notify the package author [first](https://gitlab.com/fdroid/rfp/-/issues/new) and gain your approval first @areina .

**Comment by areina** [comment]
Hello!
Thank you for your interest on this, @slackline. I don't see any problem, feel free to submit.

**Comment by slackline** [comment]
Thanks @areina request for inclusion [submitted](https://gitlab.com/fdroid/rfp/-/issues/1666).

**Comment by slackline** [comment]
@areina The submission to F-droid suggested a very minor tweak to the Gradle configuration, I've created a [pull-request](https://github.com/areina/elfeed-cljsrn/pull/17) to make it.

**Comment by ParetoOptimalDev** [comment]
FWIW I was just interested in this. Would an increased bounty increase the odds of this getting added?

**Comment by areina** [comment]
Hello @ParetoOptimalDev, 

In fact, I didn't even realize about the bounty. I have some free time these days, I'll try to take a look at this issue again and see what's possible. Thanks for the interest on this.

**Comment by areina** [comment]
It took a looong time but finally the app has been published on f-droid. [link](https://f-droid.org/es/packages/com.elfeedcljsrn/)

**Comment by slackline** [comment]
Thank you @areina for taking the time to add this to F-Droid :+1:
