### ISSUE TITLE
Removed from Google Play Store?

### ISSUE THREAD

**Issue by bhipple** [areina/elfeed-cljsrn#16]
It looks like the link to the play store is broken, and I can't find it in the search.  Is this package still maintained?  Does it work on the latest android if I download the github release and install manually?

I've setup elfeed on my desktop/laptops with syncthing syncing the database and it's wonderful, but I'm wondering what the best option for Android is in 2019?

**Comment by areina** [comment]
Hello,

yes, the application was removed from google play. Sorry for the inconvenience. I've uploaded it again and should be available to download. I use it in an Android 7 and it works well. Cheers!
