### ISSUE TITLE
Some words are squashed together

### ISSUE THREAD

**Issue by tigermonkey** [areina/elfeed-cljsrn#4]
First, thanks a lot for this tool. It is exactly what I was looking for.

One thing I have noticed is that sometimes a word is concatenated to the next one. If you look closely in the package's last screenshot, you can see what I mean. Some examples: "evaluatesthe", "computean", "couldproduce".

**Comment by areina** [comment]
You're welcome, I'm glad it's useful for someone else :-) 

It's weird, I didn't realise until you mentioned it. I will take a look and see what's happening. Thanks for your feedback!
