### ISSUE TITLE
No https?

### ISSUE THREAD

**Issue by Necronian** [areina/elfeed-cljsrn#6]
When I enter the url to my elfeed server, it complains that the url must begin with http://
I'm running elfeed behind nginx and all http traffic is automatically sent to https. Is https really not supported or is the url checker just too simplistic?

**Comment by areina** [comment]
Sorry! My fault, I introduced url validation recently and I'm checking for http://. Will try to fix it as soon as possible.

**Comment by areina** [comment]
Hi, should be fixed now. I already pushed the update to Google Play and it will probably available tomorrow for upgrade, and it's already available in GH releases. Sorry for the inconvenience

**Comment by Necronian** [comment]
Thanks, now I can give it a proper demo.
